services:
  - type: web
    name: jsa-silver-show
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
